name: Benchmarks

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

on:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: codspeed-macro
    services:
      kafka:
        image: confluentinc/cp-kafka:8.0.0
        ports:
          - 9092:9092
        env:
          KAFKA_NODE_ID: "1"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
          KAFKA_PROCESS_ROLES: "broker,controller"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_BROKER_ID: "1"
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
          KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
          KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
          KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
          CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - 5672:5672
      nats:
        image: diementros/nats:js
        ports:
          - 4222:4222
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version: "latest"
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
      - name: Install Dependencies
        run: |
          uv pip install --system --group optionals --group testing .
      - name: Install Pydantic v2
        run: uv pip install --system --prerelease=disallow "pydantic>=2.0.0,<3.0.0"
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@db35df748deb45fdef0960669f57d627c1956c30 # v4.13.1
        with:
          mode: walltime
          run: uv run pytest benchmarks/ --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}
